/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab3;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Menu men = new Menu();
    }
}
